"""add cover image public id to the column

Revision ID: 0a5eb743d656
Revises: 8bfd1250ea96
Create Date: 2026-07-08 15:03:19.430527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5eb743d656'
down_revision: Union[str, Sequence[str], None] = '8bfd1250ea96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image_public_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image_public_id')
    # ### end Alembic commands ###
