"""add avatar_public_id to users

Revision ID: 3a4e2f28c8f3
Revises: d2154def01cb
Create Date: 2026-07-04 13:10:16.016878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4e2f28c8f3'
down_revision: Union[str, Sequence[str], None] = 'd2154def01cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_public_id')
    # ### end Alembic commands ###
