"""update created_at and updated_at

Revision ID: ca5cd14b6bd0
Revises: 3a4e2f28c8f3
Create Date: 2026-07-06 12:19:01.294268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5cd14b6bd0'
down_revision: Union[str, Sequence[str], None] = '3a4e2f28c8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    # ### end Alembic commands ###
